cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

cosmetics_shop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from accounts import urls as accounts_urls
from products import urls as product_urls
from cart import urls as cart_urls
from orders import urls as orders_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include(accounts_urls)),
    url(r'^cart/', include(cart_urls, namespace='cart')),
    url(r'^orders/', include(orders_urls, namespace='orders')),
    url(r'^', include(product_urls, namespace='shop')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

orders/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^create/$', views.order_create, name='order_create'),
]

products/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'(?P<category_slug>[-\w]+)/$', views.product_list, name="product_list_by_category"),
    url(r'(?P<id>\d+)/(?P<slug>[-\w]+)$', views.product_detail, name='product_detail'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from products.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})

templates/cart/detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}Ваша корзина{% endblock %}
{% block content %}
<h1>Ваша корзина</h1>
<table class="cart">
<thead>
    <tr>
        <th>Фото товара</th>
        <th>Товар</th>
        <th>Количество</th>
        <th>Удалить</th>
        <th>Цена за единицу товара</th>
        <th>Общая цена</th>
    </tr>
</thead>
<tbody>
    {% for item in cart %}
        {% with product=item.product %}
            <tr>
            <td>
            <a href="{{ product.get_absolute_url }}">
                <img src="{% if product.image %}{{ product.image.url}}{% else %}{% static "img/nophoto.png" %}{% endif %}">
            </a>
            </td>
            <td>{{ product.name }}</td>
            <td>
                <form action="{% url "cart:cart_add" product.id %}" method="post">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.update }}
                <input type="submit" value="Обновить">
                {% csrf_token %}
                </form>
            </td>
            <td><a href="{% url "cart:cart_remove" product.id%}">Удалить</a></td>
            <td class="num">${{ item.price }}</td>
            <td class="num">${{ item.total_price }}</td>
            </tr>
        {% endwith %}
    {% endfor %}
    <tr class="total">
        <td>Общая стоимость</td>
        <td colspan="4"></td>
        <td class="num">${{ cart.get_total_price }}</td>
    </tr>
</tbody>
</table>
<p class="text-right">
<a href="{% url "shop:product_list" %}" class="button light">Продолжить покупку</a>
<a href="{% url "orders:order_create" %}" class="button">Оформить заказ</a>
</p>
{% endblock %}