cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

cosmetics_shop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from accounts import urls as accounts_urls
from products import urls as product_urls
from cart import urls as cart_urls
from orders import urls as orders_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include(accounts_urls)),
    url(r'^cart/', include(cart_urls, namespace='cart')),
    url(r'^orders/', include(orders_urls, namespace='orders')),
    url(r'^', include(product_urls, namespace='shop')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

products/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'(?P<category_slug>[-\w]+)/$', views.product_list, name="product_list_by_category"),
    url(r'(?P<id>\d+)/(?P<slug>[-\w]+)$', views.product_detail, name='product_detail'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}MyFavouriteCosmetics - сайт по продаже косметики из США и Европы{% endblock %}</title>
    <link rel="stylesheet" href="/static/main.css">
</head>
<body>


<header>
    <div id="pink-header-area">
    	<div class="upper-header-content">
        <div class="site_name">
            <h1><a href="{% url 'shop:product_list'%}">MyFavouriteCosmetics</a></h1>
        </div>
            <div class="header-auth-links">
                {% if request.user.is_authenticated %}
                    <div class="headerLink">
                    Вы вошли, как {{ request.user.first_name}} {{request.user.last_name }}
                    </div>
                    <div class="headerLink lastItem">
                    <a href="{% url "logout" %}">Выйти</a>
                    </div>
                {% else %}
                    <div class="headerLink">
                    <a href="{% url 'login' %}">Войти </a>
                    </div>
                    <div class="headerLink lastItem">
                    <a href="{% url 'registration' %}" >Регистрация</a>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
</header>
<div id="subheader">
<div class="cart">
    {% with total_items=cart|length %}
        {% if cart|length > 0 %}
        Ваша корзина:
        <a href="{% url "cart:cart_detail" %}">
        Количество товаров: {{ total_items }} ,
        На сумму: ${{ cart.get_total_price }}
        </a>
        {% else %}
        В корзине пусто
        {% endif %}
    {% endwith %}
</div>
</div>

<div id="content">
{% block content %}

{% endblock %}
</div>

<footer>

        <div class="footerarea-content">
            <div class="copyRight">
                <span>&copy; 2017 MyFavouriteCosmetics.Site is made by Nastassia Seuruk.</span>
            </div>
            <div class="footerLinks">
				<div class="footerLink">О магазине</div>
				<div class="footerLink">Оплата и доставка</div>
				<div class="footerLink lastItem">Контакты</div>
			</div>
        </div>

</footer>

</body>
</html>